### ISSUE TITLE
content 메타데이타 title에 markdown escaping 관련 이슈

### ISSUE THREAD

**Issue by awesomeo184** [zoomkoding/zoomkoding-gatsby-blog#69]
안녕하세요. 블로그 잘 사용하고 있습니다. 사용 중 한가지 이슈를 만났는데 해결이 가능한건지, 아니면 어쩔 수 없는 문제인지 궁금하여 이슈 남깁니다.

포스트를 작성할 때 최상단에 작성하는 메타데이타에 마크다운 문법을 사용하면 에러가 발생하는데요,

```
---
emoji: 📝
title: [Tech] example title
date: '2020-12-28 23:00:00'
author: tester
tags: blah
categories: blah
---
```

이렇게 작성하면 아래와 같은 에러가 뜨네요. 전체 로그입니다.

```
$ npm run deploy

> zoomkoding.com@3.0.0 deploy
> gatsby clean && gatsby build && gh-pages -d public

info Deleting .cache, public, /Users/awesomeo184/awesomeo184.github.io/node_modules/.cache/babel-loader,
/Users/awesomeo184/awesomeo184.github.io/node_modules/.cache/terser-webpack-plugin
info Successfully deleted directories

success compile gatsby files - 0.183s
success load gatsby config - 0.026s
success load plugins - 0.510s
success onPreInit - 0.002s
success initialize cache - 0.064s
success copy gatsby files - 0.080s
success Compiling Gatsby Functions - 0.131s
warn Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
success onPreBootstrap - 1.403s
success createSchemaCustomization - 0.009s

 ERROR 

Error processing Markdown file /Users/awesomeo184/awesomeo184.github.io/content/live-study-1/index.md:

      can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 5:
    date: '2020-12-28 23:00:00'
        ^

not finished source and transform nodes - 0.219s

*[master][~/awesomeo184.github.io]$ /Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0
/Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0
/Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0
/Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0
/Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0
/Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0
/Users/awesomeo184/awesomeo184.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at process.target.send (node:internal/child_process:740:16)
    at onResult (/Users/awesomeo184/awesomeo184.github.io/node_modules/gatsby-worker/dist/child.js:38:5)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/awesomeo184/awesomeo184.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:744:35
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.9.0

```

<br>

title에 마크다운 문법이 포함되어 있어서 처리가 안되는 것 같아 아래와 같이 escape 처리를 했더니 deploy가 잘 됩니다. 문제는 블로그 포스트에 escape 문자(`\`)가 그대로 나타나서 보기가 껄끄럽더라구요.

```
---
emoji: 📝
title: \[Tech] example title
date: '2020-12-28 23:00:00'
author: tester
tags: blah
categories: blah
---
```

관련 이슈에 대해 혹시 해결이 가능할까요?

**Comment by awesomeo184** [comment]
title을 홑따옴표로 감싸니 잘 되네요.

```
title: '[Tech] example title' 
```
