### ISSUE TITLE
Epipe 오류 어떻게 해결해야하나요?ㅜㅜㅜ

### ISSUE THREAD

**Issue by GYURI-PARK** [zoomkoding/zoomkoding-gatsby-blog#71]
(base) gyuri@GYURIui-MacBookAir GYURI-PARK.Github.io % npm run deploy

> GYURI-PARK@3.0.0 deploy
> gatsby build && gh-pages -d public

success compile gatsby files - 0.177s
success load gatsby config - 0.022s
warn Plugin gatsby-plugin-robots-txt is not compatible with your gatsby version 4.25.0 - It requires gatsby@^5.0.0
warn Plugin gatsby-plugin-robots-txt is not compatible with your gatsby version 4.25.0 - It requires gatsby@^5.0.0
success load plugins - 0.338s
warn gatsby-plugin-react-helmet: Gatsby now has built-in support for modifying the document head. Learn more at
https://gatsby.dev/gatsby-head
success onPreInit - 0.005s
success initialize cache - 0.013s
success copy gatsby files - 0.079s
success Compiling Gatsby Functions - 0.085s
success onPreBootstrap - 0.112s
success createSchemaCustomization - 0.008s

 ERROR 

Error processing Markdown file /Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/content/canvas-sheep on the
hill/index.md:

      can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:
    date: '2022-12-12 13:00:00'
    ^

not finished source and transform nodes - 0.231s

(base) gyuri@GYURIui-MacBookAir GYURI-PARK.Github.io % /Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0
/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0
/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0
/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0
/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0
/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0
/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:872:20)
    at process.target.send (node:internal/child_process:745:19)
    at Object.<anonymous> (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/gatsby-worker/dist/child.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/gyuri/Desktop/GitHub/GYURI-PARK.github.io/node_modules/signal-exit/index.js:199:34)
    at node:internal/child_process:876:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v19.2.0

**Comment by zoomkoding** [comment]
디펜던시 이슈를 해소했는데 관련 이슈로 보이네요. package.json, package-lock.json을 복사해서 다시 테스트 부탁드립니다!
