### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by NaMooJoon** [zoomkoding/zoomkoding-gatsby-blog#72]
안녕하세요 zoomkoding 선배님..!!

Gatsby-theme 만들고 공유해주셔서 정말 감사합니다.

개인적으로 디자인이 너무 괜찮은 것 같아서, 이 theme으로 블로그를 만들려고 하는데요..!
` npm install `
을 설치하는 데 있어 error가 발생해서 질문드립니다.

https://github.com/zoomKoding/zoomkoding-gatsby-blog/issues/16
위의 이슈도 참조해봤고, 따로 구글링을 통해 문제 해결해보려 했는데 아직 해결하지 못하여
이렇게 질문 드립니다..

https://www.zoomkoding.com/gatsby-github-blog/
에 나와 있는 대로 순서대로 모두 진행하다가 `npm install`에서 막혔습니다..

현재 제 컴퓨터는 mac m1, Monterey 12.0.1이고, npm 버전은 다음과 같습니다.
> node --version: v19.3.0
> npm --version: 9.2.0

에러 메시지는 다음과 같습니다.
```bash
>> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: gatsby-plugin-advanced-sitemap@2.0.0
npm ERR! Found: gatsby@4.9.3
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^4.9.3" from the root project
npm ERR!   peer gatsby@"^4.0.0-next" from babel-plugin-remove-graphql-queries@4.9.1
npm ERR!   node_modules/babel-plugin-remove-graphql-queries
npm ERR!     babel-plugin-remove-graphql-queries@"^4.9.1" from gatsby@4.9.3
npm ERR!     babel-plugin-remove-graphql-queries@"^4.9.1" from gatsby-plugin-image@2.9.1
npm ERR!     node_modules/gatsby-plugin-image
npm ERR!       gatsby-plugin-image@"^2.9.1" from the root project
npm ERR!     1 more (gatsby-plugin-typescript)
npm ERR!   26 more (gatsby-material-ui-components, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^3.0.0" from gatsby-plugin-advanced-sitemap@2.0.0
npm ERR! node_modules/gatsby-plugin-advanced-sitemap
npm ERR!   gatsby-plugin-advanced-sitemap@"^2.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: gatsby@3.15.0
npm ERR! node_modules/gatsby
npm ERR!   peer gatsby@"^3.0.0" from gatsby-plugin-advanced-sitemap@2.0.0
npm ERR!   node_modules/gatsby-plugin-advanced-sitemap
npm ERR!     gatsby-plugin-advanced-sitemap@"^2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/joonk/.npm/_logs/2022-12-29T07_30_07_156Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joonk/.npm/_logs/2022-12-29T07_30_07_156Z-debug-0.log
```

다음은 `npm install --verbose`로 실행시킨 내용입니다.
```bash
npm verb cli /opt/homebrew/Cellar/node/19.3.0/bin/node /opt/homebrew/bin/npm
npm info using npm@9.2.0
npm info using node@v19.3.0
npm verb title npm install
npm verb argv "install" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/joonk/.npm/_logs/2022-12-29T07_36_07_456Z-
npm verb logfile /Users/joonk/.npm/_logs/2022-12-29T07_36_07_456Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/gatsby 128ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/react 30ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/react-dom 45ms (cache revalidated)
npm verb stack Error: could not resolve
npm verb stack     at PlaceDep.failPeerConflict (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:502:25)
npm verb stack     at new PlaceDep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:156:21)
npm verb stack     at /opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:942:31
npm verb stack     at Array.map (<anonymous>)
npm verb stack     at [buildDepStep] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:942:8)
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:156:5)
npm verb stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:146:5)
npm verb cwd /Users/joonk/blog/blog.github.io
npm verb Darwin 21.1.0
npm verb node v19.3.0
npm verb npm  v9.2.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: gatsby-plugin-advanced-sitemap@2.0.0
npm ERR! Found: gatsby@4.9.3
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^4.9.3" from the root project
npm ERR!   peer gatsby@"^4.0.0-next" from babel-plugin-remove-graphql-queries@4.9.1
npm ERR!   node_modules/babel-plugin-remove-graphql-queries
npm ERR!     babel-plugin-remove-graphql-queries@"^4.9.1" from gatsby@4.9.3
npm ERR!     babel-plugin-remove-graphql-queries@"^4.9.1" from gatsby-plugin-image@2.9.1
npm ERR!     node_modules/gatsby-plugin-image
npm ERR!       gatsby-plugin-image@"^2.9.1" from the root project
npm ERR!     1 more (gatsby-plugin-typescript)
npm ERR!   26 more (gatsby-material-ui-components, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^3.0.0" from gatsby-plugin-advanced-sitemap@2.0.0
npm ERR! node_modules/gatsby-plugin-advanced-sitemap
npm ERR!   gatsby-plugin-advanced-sitemap@"^2.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: gatsby@3.15.0
npm ERR! node_modules/gatsby
npm ERR!   peer gatsby@"^3.0.0" from gatsby-plugin-advanced-sitemap@2.0.0
npm ERR!   node_modules/gatsby-plugin-advanced-sitemap
npm ERR!     gatsby-plugin-advanced-sitemap@"^2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/joonk/.npm/_logs/2022-12-29T07_36_07_456Z-eresolve-report.txt
npm verb exit 1
npm verb unfinished npm timer reify 1672299367489
npm verb unfinished npm timer reify:loadTrees 1672299367489
npm verb unfinished npm timer idealTree:buildDeps 1672299367971
npm verb unfinished npm timer idealTree:node_modules/gatsby-plugin-advanced-sitemap 1672299367971
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joonk/.npm/_logs/2022-12-29T07_36_07_456Z-debug-0.log
```

<br>
구글링을 해보니.. npm install문제는 dependancy가 안맞을 경우가 많다고 해서 `npm install --force`로도 실행해봤습니다만, WARN 뜨며 전부 설치 되는 것 처럼 보이더니 마지막에 설치가 안됩니다..
<img width="1037" alt="Screen Shot 2022-12-29 at 4 41 00 PM" src="https://user-images.githubusercontent.com/47983023/209919442-a6e711ed-6d89-495d-b7ed-6413cefdad9f.png">

혹시 어떤게 문제인지 알 수 있을까요..?
간단한 설치 문제가지고 이슈 남기게 되어 죄송합니다.

감사합니다.

**Comment by kim228sy** [comment]
안녕하세요, NaMooJoon님!
버전의 문제 같습니다.

현재 제 버전은 이렇습니다.
> node --version: v18.13.0
> npm --version: 8.19.3

`nvm install --lts`로 node LTS 최신버전 설치하시고,
그래도 되지 않으시면 `npm install -g npm@latest`로 npm 버전을 변경 해보셔도 좋을 거 같습니다.
그 후 위에 적으신 것과 같이
`npm install --force`, `npm install gh-pages --save-dev --force` 진행 하시면 될 듯합니다.
즐거운 코딩생활 되세요👍

**Comment by kim228sy** [comment]
안녕하세요, NaMooJoon님!
역으로 node 버전이 너무 최신이라 생기는 문제 같습니다.

이 버전으로 변경 후엔 정상 작동합니다.
> node --version: v18.13.0

`nvm install --lts`로 node LTS 최신버전 설치하시면 됩니다.

즐거운 코딩생활 되세요👍

**Comment by zoomkoding** [comment]
답변 늦어 죄송합니다. 패키지 설치 관련 이슈 해결했습니다.
